version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Replace with your email
      PGADMIN_DEFAULT_PASSWORD: admin  # Replace with your secure password
    ports:
      - "8081:80"  # Mapping host port 8081 to container port 80
    depends_on:
      - postgres

volumes:
  postgres_data:
